### ISSUE TITLE
AssetBundle 構築の前処理や後処理が呼び出されない

### ISSUE THREAD

**Issue by fakestarbaby** [umm-projects/simple_build#27]
## 💀 問題
Assembly Definition 対応にて、`Assembly-CSharp-Editor.dll` 以外の dll に前処理や後処理が含まれるようになったことにより、`IPreprocessBuildAssetBundle` や `IPostprocessBuildAssetBundle` を持つインスタンスを読み込めず、呼び出されなくなってしまっている。

**Comment by monry** [comment]
あー、こっちもか…。

**Comment by fakestarbaby** [comment]
こっちも、ということは、同じような対応どっかで入れてたのかな。

**Comment by monry** [comment]
この PR みたいな感じで、全 Assembly 引っ張っちゃって、その中から `IPreprocessBuildAssetBundle` やら `IPostprocessBuildAssetBundle` やらを実装してるクラスをフィルタする感じでヨサソウ。

**Comment by fakestarbaby** [comment]
試してみます！

**Comment by monry** [comment]
🙏 ｽﾏﾇｰ
